/*
* generated by Xtext
*/
package robot.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import robot.services.DeviceGrammarAccess;

public class DeviceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DeviceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected robot.parser.antlr.internal.InternalDeviceParser createParser(XtextTokenStream stream) {
		return new robot.parser.antlr.internal.InternalDeviceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Types";
	}
	
	public DeviceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DeviceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
