/*
 * generated by Xtext
 */
package robot.ui.contentassist

import robot.ui.contentassist.AbstractDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DslProposalProvider extends AbstractDslProposalProvider {
}
