/**
 * generated by Xtext
 */
package robot.ui.contentassist;

import robot.ui.contentassist.AbstractDeviceProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DeviceProposalProvider extends AbstractDeviceProposalProvider {
}
