/*
 * generated by Xtext
 */
package robot;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DeviceRuntimeModule extends robot.AbstractDeviceRuntimeModule {

}
