/*
* generated by Xtext
*/
package robot;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DeviceStandaloneSetup extends DeviceStandaloneSetupGenerated{

	public static void doSetup() {
		new DeviceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

