/*
* generated by Xtext
*/
package robot;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return robot.ui.internal.DslActivator.getInstance().getInjector("robot.Dsl");
	}
	
}
