/*
* generated by Xtext
*/
package robot;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DeviceUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return robot.ui.internal.DeviceActivator.getInstance().getInjector("robot.Device");
	}
	
}
